name: Java CI with Maven

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/webapp?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=America/Los_Angeles&allowMultiQueries=true
  SPRING_DATASOURCE_USERNAME: Karl
  SPRING_DATASOURCE_PASSWORD: 1234

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0.32
        ports:
          - 3306:3306
        env:
          MYSQL_USER: 'Karl'
          MYSQL_PASSWORD: '1234'
          MYSQL_DATABASE: 'webapp'
          MYSQL_ROOT_PASSWORD: 'root'
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn compile

      - name: Run Unit Test with Maven
        run: mvn -B test --file pom.xml
      
      - name: Start mysql services
        # run: sudo systemctl start mysql
        run: sudo journalctl -xeu mysql.service

      - name: Package with Maven
        run: mvn -B package --file pom.xml

      - name: Install Packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "1.8.6"

      - name: Validate Packer Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: "validate"
          target: "ami.pkr.hcl"
        env:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
