name: Build AMI

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  Build_AMI:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Unit Test with Maven
        run: mvn -B test --file pom.xml

      - name: Package with Maven
        run: mvn package

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Install Packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "1.8.6"

      - name: Build AMI
        run: packer build ami.pkr.hcl
