# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
    pull_request:
      branches:
        - main
        
env:
  PKR_VAR_ami-user-default: 507902230172
  PKR_VAR_auth-key: ${{ secrets.AUTH_KEY }}
  PKR_VAR_auth-secret-key: ${{ secrets.AUTH_SECRET_KEY }}
  PKR_VAR_default-region: ${{ secrets.REGION }}
  PKR_VAR_default-ami: ami-0f1a5f5ada0e7da53
  PKR_VAR_vpc-id: vpc-015b941b9484f46bd
  PKR_VAR_subnet-id: subnet-04b58ab02e84d3226
  PKR_VAR_sg-id: sg-052d9ec70a4403055
  
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_DRIVE: ${{ secrets.DB_DRIVE }}
  DB_URL: ${{ secrets.DB_URL }}

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        
    - name: Setup MySQL
  # You may pin to the exact commit or the version.
  # uses: mirromutth/mysql-action@de1fba8b3f90ce8db80f663a7043be3cf3231248
      uses: mirromutth/mysql-action@v1.1
      with:
    # The port of host
        host port: 3306
    # Version of MySQL to use
        mysql version: 5.7
        mysql root password: ${{ secrets.DB_PASSWORD }}
    # MYSQL_DATABASE - name for the default database that is created
        mysql database: TestDev
        
    - name: Build with Maven
      run: mvn -B package --file liu-station-spring/pom.xml
    
    - name: Get Name
      run: whoami
      
    - name: Print Current Path
      run: pwd
      
    - name: make new Dir
      run: mkdir newdir
      
    - name: Enter new Dir
      run: cd newdir

    - name: Print Current Path
      run: pwd
      
    - name: Packer Init
      run: packer init hashicorp/09
      
    - name: Packer Run
      run: packer build hashicorp/09/aws-instance-lrl-6225.pkr.hcl
      
    - name: Hello world
      run: echo "Hello world"
      
    - name: Verify AMI
      run: packer build 

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
